services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes: 
      -  postgres_db:/var/lib/postgresql/data

  node_sorteador_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - .env

volumes:
   postgres_db: